version: '3'
services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_ws:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: webhook_system
    volumes:
      - postgres-db-volume_ws:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD", "pg_isready", "-U", "admin"]
#      interval: 10s
#      retries: 5
#      start_period: 5s
    ports:
      - "5432:5432"
    restart: always
  redis_container:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache_ws:/data
  redisinsight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_db_ws:/db
  rabiitmq_container:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_data_ws:/var/lib/rabbitmq/
      - rabbit_log_ws:/var/log/rabbitmq

volumes:
  postgres-db-volume_ws:
  rabbit_data_ws:
  rabbit_log_ws:
  redisinsight_db_ws:
  cache_ws:
  pgadmin_ws:
